#!/usr/bin/env python
# coding: utf8

import argparse
from subprocess import Popen, PIPE
import sys
import re

RgFlagCat = re.compile('^\[ [a-z]+ \]')
RgFlagDefault = re.compile('\[ defaults \]')
RgFlagAtomType = re.compile('\[ atomtypes \]')


def ReadTopFile(Filename) :
    """
    Read a gromacs top file and add or delete informations.
    FROM MAUD jusot
    """
    Flag = 0
    newFile = ''
    with open(Filename, 'r') as filin :
        for li in filin :
            if RgFlagCat.search(li) :
                if RgFlagDefault.search(li) or RgFlagAtomType.search(li) :
                    Flag = 1
                else :
                    Flag = 0
            if Flag == 0 :
                newFile += li
            elif Flag == 1 :
                newFile += ';'
                newFile += li
            else :
                print "Error in Flag"
    return newFile


def WriteNewFile(Filename, newFile, forceField="96") :
	"""
	Write a new file readable for gromacs.
	From MAUD jusot
	"""
	with open(Filename.replace(".top", "_corrected.top"),'w') as filout :
		filout.write(';force field\n#include "amber')
		filout.write(str(forceField))
		filout.write('.ff/forcefield.itp"\n\n')
		filout.write(newFile)


def Regex4topol(line, topfile):
    """
    Modify order atoms to correct improper dihedral
    """
    AtomID = {}
    atomName = line.split(";")[1]
    atomNumber = line.split(";")[0]
    for i in xrange(len(atomName.split())):
        AtomID[atomName.split()[i]] = atomNumber.split()[i]
    if line.split(";")[1].split()[0][0] == "N":
        #Modifiy initial order of N-    CA-     C-     O to CA-     N-     C-     O
        newline = '{0:>6} {1:>6} {2:>6} {3:>6}'.format(AtomID["CA-"], AtomID["N-"], AtomID["C-"],AtomID["O"])
    elif line.split(";")[1].split()[0][0] == "H":
        #Modifiy initial order of H-     N-     C-    CA to C-    CA     N-     H
        newline = '{0:>6} {1:>6} {2:>6} {3:>6}'.format(AtomID["C-"], AtomID["CA"], AtomID["N-"],AtomID["H-"])
    else:
        print "Regex not found !\nPlease send a email with your PDB file"
        print line
        sys.exit(0)
    newline = newline+line[27:]
    cmd = "sed -i \"s/"+line[:-1]+"/"+newline[:-1]+"/\" "+topfile
    Popen(cmd, shell=True).wait()


def CorrectDihedral(topfile):
    """
    Amber define a wrong improper dihedral (the fisrt one)
    The function modify topology file to correct it
    Argument:
        _topfile: GROMACS topology generated by acpype (from amber topology)
    """
    flag = False
    cpt = 0
    with open(topfile, "r") as filin:
        for line in filin:
            if line[:-1] == "[ dihedrals ] ; impropers":
                flag = True
                continue
            elif flag is True and line[0] == ";":
                continue
            elif flag is True and line[0] != ";":
                print line
                tmp = line
                cpt += 1
                Regex4topol(line, topfile)
                if cpt > 1:
                    flag = False

def CorrectFirstRes(groFile):
    with open(groFile, "r") as file:
        for line in file:
            #print line
            if len(line.split()) != 7:
                continue
            else:
                if line.split()[1] == "PRO":
                    #first amino acid is a proline, no need to correct topology file
                    return False
                else:
                    return True

def makeTopology(structure, peptide, gmx, tleap, acpype, forcefield):
    """
    Generate topopoly files for gromacs from intial structure
    Arguments:
        _structure: PDB file
        _peptide: Flag to specify if the peptide is cyclic or not
        _gmx: path for gromacs
        _tleap: path for leap
    Return:
        peptide.gro: structure file
        peptide.top: topology file
    """
    if peptide == False:
        print "No cyclic peptide"
        cmd = gmx+" pdb2gmx -p peptide.top -ignh yes -ff "+forcefield+" -water none\
     -o peptide.gro -f "+structure
        Popen(cmd, shell=True).wait()
    else:
        print "Cyclic peptide"
        #First step we remove hhydrogen
        Popen("grep -v 'H' "+structure+" > pept-H.pdb", shell=True).wait()
        #Atoms's number beging at 1
        Popen(gmx+" editconf -f pept-H.pdb -o pept-good.pdb -resnr 1", shell=True).wait()
        p1= Popen("grep 'CA' pept-good.pdb | tail -n 1", stdout=PIPE, shell=True)
        output = p1.communicate()
        residue = output[0][22:26]
        #Create leap script to generate amber topology files
        #gromacs can not make correct topology file for cyclic peptide)
        print("generate script for amber")
        with open("script.leap", "w") as filin:
            filin.write("source "+tleap)
            filin.write("\nset default PBradii bondi")
            filin.write("\nclearpdbresmap")
            filin.write("\nmol = loadpdb pept-good.pdb")
            print "\nbond mol.1.N mol."+residue.strip(" ")+".C"
            filin.write("\nbond mol.1.N mol."+residue.strip(" ")+".C")
            filin.write("\nsaveamberparm mol pept_amber.prmtop pept_amber.inpcrd")
            filin.write("\nsavepdb mol pept_amber.pdb")
            filin.write("\nquit")
        print("generate amber's topology")
        Popen("tleap -f script.leap", shell=True).wait()
        #delete unacessary files
        Popen("rm ./pept-H.pdb ./pept-good.pdb ./pept_amber.pdb", shell=True).wait()
        Popen(acpype+" -x pept_amber.inpcrd -p pept_amber.prmtop", shell=True).wait()
        #If the first residu is a proline, no need to correct topology file
        NewFile = ReadTopFile("pept_amber_GMX.top")
        WriteNewFile("pept_amber_GMX.top", NewFile)
        Popen("rm ./pept_amber.inpcrd ./pept_amber.prmtop ./pept_amber_GMX.top", shell=True).wait()
        if CorrectFirstRes("pept_amber_GMX.gro"):
            CorrectDihedral(NewFile)
        Popen("mv pept_amber_GMX.gro peptide.gro", shell=True).wait()
        Popen("mv pept_amber_GMX_corrected.top peptide.top", shell=True).wait()
    return "peptide.gro", "peptide.top"



if __name__ == '__main__':
    #path for gromacs
    gmx="/usr/local/gromacs/bin/gmx_mpi"
    #path for the force field
    leap="/amber18/dat/leap/cmd/oldff/leaprc.ff96"
    acpype="/home/REMD/src/acpype.py"
    parser = argparse.ArgumentParser(description='topology fie (GRO,PDB)')
    parser.add_argument('-g', action="store", dest="g", type=str, help="pdb file", default= None)
    parser.add_argument('-cyclic', action="store", dest="cyclic",default=False, type=bool, help="flag for cyclic peptide")
    parser.add_argument('-o', action="store", dest="o", type=str, default = "./",\
    help="output path filename ")
    arg = parser.parse_args()
    pdb = arg.g

    if pdb[-3:] != "pdb":
        print "please provide a PDB file"
        sys.exit(0)
    pdb, topology = MakeTopology(pdb, arg.cyclic, gmx, leap, acpype, "amber96")
